---
title: "EAD"
author: "Eligijus Bujokas"
date: "12/27/2020"
output: html_document
---

```{r setup, include=FALSE}
library(betareg)
library(data.table)
library(pROC)
library(ROCR)
library(ggplot2)
library(gridExtra)
```

# Reading data 

```{r reading data}
train <- fread('data/train_defaults.csv')
test <- fread('data/test_defaults.csv')

print(head(train))
print(head(test))

print(nrow(train))
print(nrow(test))

# Droping NA 
train = na.omit(train)

# Ensuring the correct data types 
train$term <- as.factor(train$term)
train$emp_length <- as.factor(train$emp_length)
train$home_ownership <- as.factor(train$home_ownership)
train$purpose <- as.factor(train$purpose)
train$verification_status <- as.factor(train$verification_status)
train$addr_state <- as.factor(train$addr_state)
train$initial_list_status <- as.factor(train$initial_list_status)
train$hardship_flag <- as.factor(train$hardship_flag)
train$grade <- as.factor(train$grade)

summary(train)
```

# Creating the model 

```{r}
colsModeling = c(
  "term",
  "pub_rec",
  "annual_inc",
  "dti",
  "month_diff",
  "emp_length",
  "int_rate",
  "loan_amnt",
  'verification_status',
  'delinq_2yrs',
  'initial_list_status'
)

X <- train[, ..colsModeling]

# Final feature list 
featuresFinal = names(X)

# Appending the Y
X$Y <- train$CCF

X$Y <- ifelse(X$Y==1, 0.999, X$Y)
X$Y <- ifelse(X$Y==0, 0.001, X$Y)

modelEAD <- betareg(Y ~ ., data=X)

# Saving the coefficients
EADcoefs <- data.table(feature=names(modelEAD$coefficients$mean), coef=modelEAD$coefficients$mean)

print(EADcoefs)
```

## Measuring results

```{r}
Xtest <- test[, ..colsModeling]

yhat_rate <- predict(modelEAD, Xtest)

# Saving to the test set 
test$CCF_hat <- yhat_rate

# Calculating the residuals
test$res <- test$CCF - test$CCF_hat

# Ploting the residuals 
hist(modelEAD$residuals, breaks=40)

p1 <- ggplot(data=test, aes(x=CCF)) + geom_histogram(fill='steelblue', color='black') + ggtitle('True distribution')
p2 <- ggplot(data=test, aes(x=CCF_hat)) + geom_histogram(fill='salmon1', color='black') + ggtitle('Predicted distribution')
p3 <- ggplot(test, aes(x=res)) + geom_density() + ggtitle("Distribution of residuals")

grid.arrange(p1, p2, p3, nrow = 1)

print(paste("MAE:", sum(abs(test$res))/nrow(test)))
```